### ISSUE TITLE
Image.shrink - selecting the max instead of average

### ISSUE THREAD

**Issue by jflat06** [libvips/pyvips#150]
Hi, I am trying to resize an image down by a factor of 2. It seems shrink does this nicely.

However, in my specific situation, I need to select the maximum value in the 2x2 block, instead of averaging these 4 pixels. 

Is there any way to do this? I can't seem to find one.

**Comment by jcupitt** [comment]
Hello @jflat06,

The best way would probably be to subclass `VipsInterpolate` and define your own max-of-4 function. You'd need to be quite a strong C programmer.

A quick hack would be to run a 2x2 rank filter on the image, then shrink by 2 with nearest-neighbour. It wouldn't be that quick, since you'd be calculating intermediate values you never used, but it would work.

```python
def shrink_max(image):
    return image.rank(2, 2, 3).reduce(2, 2, kernel="nearest")
```

dzsave can do 2x2 shrinks with mean, median and mode, but not max. There's an enhancement to add max and min, but it's not been implemented yet.

**Comment by jflat06** [comment]
Thanks for the suggestion! I tried this out and it appears to work. 

I ended up writing a custom solution in PIL/numpy that performs a bit better, but this is a good sanity check between the two.
