### ISSUE TITLE
[Question] Setting metadata values does not update?

### ISSUE THREAD

**Issue by jclavoie-jive** [libvips/pyvips#161]
Hello! It is my first time playing with vips. I am trying to join images together and save them in multiple pages (similar to what `gm convert [...] -adjoin` would do)

From [this](https://github.com/libvips/libvips/issues/789) I tried to set the `page-height` value. However, although I do not get errors when calling `set_type`, the value isn't updated. 

This is my code 
```
import pyvips

a = pyvips.Image.new_from_file('test.tiff', access='sequential')
b = pyvips.Image.new_from_file('test.tiff', access='sequential')
c = a.join(b, 'vertical')
c.set_type(pyvips.GValue.gint_type, 'page-height', a.height)
print c.get('page-height')
c.tiffsave('test_pyvips.tiff')
```

print c.get('page-height') generates an exception saying the field does not exist.

Anything I would be missing? Thanks in advance for your help!
FYI I am using vips-8.9.1 on OS X and python2.7

**Comment by jcupitt** [comment]
Hello @jclavoie-jive,

This is a change for 8.9: you can no longer set metadata on images which might be shared between threads, since it can cause crashes. 

Instead, copy your image before setting metadata, something like:

```python
c = c.copy()
c.set_type(pyvips.GValue.gint_type, 'page-height', a.height)
```

That'll make sure you have a private copy of the image and you can modify it.

**Comment by jclavoie-jive** [comment]
It's working. Thanks!
