### ISSUE TITLE
Resize at width as well as height

### ISSUE THREAD

**Issue by KVishnuVardhanR** [libvips/pyvips#344]
Hi,
I want to resize a huge .tif image based on its width and height using pyvips
This is the sample code I use to resize an image using opencv.

`cv2.resize(image,(int(image.shape[1]/33),int(image.shape[0]/33)),interpolation= cv.INTER_LINEAR)`

Is there a way where we can resize huge .tif files based on both width and height dimensions using pyvips ?
Thanks for your help!
Vishnu

**Comment by KVishnuVardhanR** [comment]
got it, 
we can actually resize using shrink method. 
`resized_image = image.shrink(33,33)`

**Comment by jcupitt** [comment]
`shrink` is a simple box filter (each pixel is the average of the NxM pixels in the input), so it's very fast, but quality is not good. Use `resize` for a high quality result, eg.

```python
out = in.resize(1.0 / 33.0, vscale=1.0 / 33.0)
```

But that will be slow for many image types. It's best to use `thumbnail`, eg.:

```
small = pyvips.Image.thumbnail("huge.tif", target_width, height=target_height, size="force")
```

Because it combines load and resize in one operation, `thumbnail` can exploit many tricks in the image format.
