### ISSUE TITLE
Write_to_image with zstd compression: "ZSTD compression support is not configured"

### ISSUE THREAD

**Issue by pmascalchi** [libvips/pyvips#432]
Hello,

I'm trying to figure out how compression libs need to be setup but I couldn't find code examples.
I looked at several pages among the great:
https://www.libvips.org/API/current/VipsForeignSave.html#vips-tiffsave

When I run something like:
`final_image.write_to_file(out_path, compression='zstd', level=0, miniswhite=False, bigtiff=True)`

I get this type of error message:
`target output: ZSTD compression support is not configured`

Vips package tested: [vips-dev-w64-all-8.14.5.zip ](https://github.com/libvips/build-win64-mxe/releases/tag/v8.14.5)

Any advice on how to configure zstd or other compression methods?

Thanks!

**Comment by jcupitt** [comment]
Hi @pmascalchi,

You need to configure zstd compression when you build libtiff, so you'll need to rebuild everything from source. I'd start with:

https://github.com/libvips/build-win64-mxe

Or alternatively, use ubuntu under wsl2, since ubuntu comes with libvips, and their tibtiff has zstd compression enabled. It's just:

```
$ sudo apt install libvips-tools
$ vips copy k2.jpg x.tif[compression=zstd]
```

**Comment by pmascalchi** [comment]
Hi @jcupitt, 

Thanks a lot for the explanation, makes more sense now :)

**Comment by pmascalchi** [comment]
Hi @jcupitt,

Thanks a lot for the explanation, makes more sense now :)
