### ISSUE TITLE
new_from_memory causes "RuntimeError: cannot use string() on <cdata 'char *' NULL>"

### ISSUE THREAD

**Issue by lk-jeffpeck** [libvips/pyvips#63]
I am doing the following:

```
import logging
logging.basicConfig(level = logging.DEBUG)

import numpy as np
import pyvips

print("pyvips version: ", pyvips.__version__)

arr = np.array([[-1, -1, -1],
                [-1, 16, -1],
                [-1, -1, -1]])

height, width = arr.shape
bands = 1
linear = arr.reshape(width * height * bands)
vi = pyvips.Image.new_from_memory(linear.data, width, height, bands, 'uchar')
```

The result is:
```
DEBUG:pyvips:Loaded binary module _libvips
DEBUG:pyvips:Inited libvips
DEBUG:pyvips:
pyvips version:  2.1.2

(pyv.py:52631): GLib-GObject-WARNING **: 15:58:03.238: cannot retrieve class for invalid (unclassed) type '<invalid>'
Traceback (most recent call last):
  File "pyv.py", line 16, in <module>
    vi = pyvips.Image.new_from_memory(linear.data, width, height, bands, 'uchar')
  File "/usr/local/miniconda3/envs/apollo_env/lib/python3.6/site-packages/pyvips/vimage.py", line 332, in new_from_memory
    format_value = GValue.to_enum(GValue.format_type, format)
  File "/usr/local/miniconda3/envs/apollo_env/lib/python3.6/site-packages/pyvips/gvalue.py", line 105, in to_enum
    format(value, type_name(gtype), gtype))
  File "/usr/local/miniconda3/envs/apollo_env/lib/python3.6/site-packages/pyvips/base.py", line 71, in type_name
    return _to_string(ffi.string(gobject_lib.g_type_name(gtype)))
RuntimeError: cannot use string() on <cdata 'char *' NULL>
```

I am using vips 8.6.5 on MacOS X:
```
$ vips -v
vips-8.6.5-Wed Jul 25 09:46:22 UTC 2018
```

**Comment by lk-jeffpeck** [comment]
Note, this is inside a conda env. I have found that outside the conda env it works, _and_ that copying `site-packages/_libvips.abi3.so` from the other env into this conda env, it will work.

But, cleanly installing pyvips into that env will cause this failure again.

**Comment by jcupitt** [comment]
Hello @lk-jeffpeck,

Yes, conda needs a special package, it won't work with the standard pyvips one. There have been a couple of tries at packaging libvips and pyvips for conda, but it hasn't worked out yet.

**Comment by lk-jeffpeck** [comment]
Aha! Interesting... What is the issue?

Since it does technically work by installing it outside of the conda env and then copying the lib, I would think that there should be a more automated way to work around the issue?

**Comment by lk-jeffpeck** [comment]
And is this documented anywhere?

**Comment by jcupitt** [comment]
I expect you know much more about this than I do, but my understanding is that conda ships its own Python and that they don't include the development headers. So you need to install a matching version of Py, but with the headers, then build the extension with compiler flags that match the way that conda built their py, then copy the extension in to the conda py module area. 

pyvips will work in ABI mode and run without a native module, but it's a bit slower. 

There's a related problem with libvips itself: it depends on things like libjpeg, and conda also ship their own versions of libraries like these. What if libvips and conda have been built against external libraries which are not binary compatible? You can get a whole range of strange crashes as code calls a library it is not expecting. 

The fix is to make a special conda package that builds libvips and also builds pyvips, then installs them together as a single binary which is compatible with your conda Python. This is the thing that's not been done yet (as far as I know). 

conda is it's own special world and you can't really use external libraries of modules with it directly. This has advantages for simplicity, stability and consistency, but can be frustrating too.

I don't use conda myself and don't know a lot about it, but it seems it's quite popular, especially on Windows. There should probably be a note about this in the pyvips README.
