### ISSUE TITLE
Is there a way to get a single deepzoom tile?

### ISSUE THREAD

**Issue by itachi1232gg** [libvips/pyvips#97]
I am developing a web application which is used to display very large medical slides.  I knew there's a `dzsave` method which can be used to generates dzi tiles fast, but dzi files use excessive disk space. Is there a method that I can get tiles dynamically, like `getTile(x,y,z) -> x_y_z.jpeg`

I tried to implemented it:
` image = pyvips.Image.new_from_file(filename)`
`tile = image.extract_area(x,y,w,h)`
`resized_tile = tile.resize(1/2**(maxlevel-z)`
`np_img = vips2numpy(resized_tile)`

it can generate tiles as expected, however this is super slow, takes 1~30 secondes to get a tile.

**Comment by jcupitt** [comment]
You can get the levels from the openslide file like this:

```python
level = pyvips.Image.new_from_file(filename, level=2)
```

And skip the resize. It should be pretty quick, especially if you reuse the `level` variable, rather than reopening all the time. You can use metadata on the image to work out the size of each of the levels:

```
$ vipsheader -a 2013_09_20_29.ndpi | grep openslide
2013_09_20_29.ndpi: 118784x102400 uchar, 4 bands, rgb, openslideload
vips-loader: openslideload
openslide.level-count: 11
openslide.level[0].downsample: 1
openslide.level[0].height: 102400
openslide.level[0].tile-height: 8
openslide.level[0].tile-width: 4096
openslide.level[0].width: 118784
openslide.level[10].downsample: 1024
openslide.level[10].height: 100
openslide.level[10].tile-height: 1
openslide.level[10].tile-width: 4
openslide.level[10].width: 116
... etc.
```

There was a very similar issue last week:

https://github.com/libvips/libvips/issues/1292
